version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - webapp
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - webapp
networks:
  webapp:
    driver: bridge
